### ISSUE TITLE
Releases and MHR/MHR.JSON files.

### ISSUE THREAD

**Issue by TritechOS** [zeozeozeo/zcb3#7]
Hi there,
I'm not quite sure why this happens, but with Megahack replay macros (probably more specifically the frame fix macros), they have beautiful clicks, but the releases just don't seem to render. Is there a reason behind this, or is it fixable?
Thanks.

**Comment by zeozeozeo** [comment]
hey, can you please send the replay file you used? i'll look into it

**Comment by TritechOS** [comment]
I've joined the discord and dropped the file.

**Comment by zeozeozeo** [comment]
this wasn't an issue with zcb, it was an issue with the macro
hold your mouse for longer or use a higher speedhack value
maybe an option to offset clicks/releases will be added for the macro converter

**Comment by TritechOS** [comment]
Right, I see. I'll try rebotting things another time and see if that's the case.
